# Copyright 2026 Sudo Sweden AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: release-please
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        uses: sudoswedenab/sudo-actions/release-please@main

  build-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::075899289117:role/GithubActionsDockyardsWorkloadTemplates
      - uses: aws-actions/amazon-ecr-login@v2.0.1
        id: login
        with:
          registry-type: public
      - uses: fluxcd/flux2/action@v2.5.1
        with:
          version: v2.4.0
      - shell: bash
        run: |
          #!/usr/bin/env bash
          flux push artifact "oci://${{steps.login.outputs.registry}}/sudosweden/dockyards-workload-templates:${{needs.release-please.outputs.tag_name}}-manifests" \
            --path manifests --source "${{github.repositoryUrl}}" --revision "${{needs.release-please.outputs.tag_name}}@sha1:${{github.sha}}"
